[package]
name = "aphrodite-mela"
version = "0.1.3"
description = "A computer-use friendly design workbench"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
base64 = "0.22"
serde_json = "1"
tempfile = "3"
fs2 = "0.4"
