import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialProject} from '../src/model';
import {readLibrary,writeLibrary,upsertProject,cloneProject,visibleEntries,LIBRARY_KEY,LEGACY_KEY} from '../src/workspace/library';
function memory(){const values=new Map<string,string>();return {values,getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);}};}
test('legacy migration preserves original bytes and edits are isolated',()=>{const s=memory(),p=initialProject(),raw=JSON.stringify(p);s.setItem(LEGACY_KEY,raw);const lib=readLibrary(s);assert.equal(s.getItem(LIBRARY_KEY),null);const copy=cloneProject(p);copy.pages[0].name='Independent';const next=upsertProject(lib,copy);writeLibrary(s,next);assert.equal(s.getItem(LEGACY_KEY),raw);assert.equal(readLibrary(s).entries.length,2);assert.notEqual(lib.entries[0].project.pages[0].name,'Independent');assert.notEqual(copy.id,p.id);assert.equal(copy.approvedFingerprint,undefined);});
test('archive, favorites and search compose without deleting entries',()=>{const p=initialProject();p.name='Paper Muse';const lib=upsertProject({version:1,entries:[]},p);lib.entries[0].pinned=true;assert.equal(visibleEntries(lib,'pinned','paper').length,1);lib.entries[0].archived=true;assert.equal(visibleEntries(lib,'recent','').length,0);assert.equal(visibleEntries(lib,'archived','MUSE').length,1);assert.equal(lib.entries.length,1);});
test('corrupt library fails closed instead of falling back over it',()=>{const s=memory();s.setItem(LEGACY_KEY,JSON.stringify(initialProject()));s.setItem(LIBRARY_KEY,'broken');assert.throws(()=>readLibrary(s));assert.equal(s.getItem(LIBRARY_KEY),'broken');});
test('failed write leaves stored library intact',()=>{const s=memory();const lib=upsertProject({version:1,entries:[]},initialProject());writeLibrary(s,lib);const before=s.getItem(LIBRARY_KEY);const fail={getItem:s.getItem,setItem:()=>{throw new Error('quota');}};assert.throws(()=>writeLibrary(fail,upsertProject(lib,initialProject())));assert.equal(s.getItem(LIBRARY_KEY),before);});
test('duplicate project ids rejected on load',()=>{const s=memory(),lib=upsertProject({version:1,entries:[]},initialProject());lib.entries.push(lib.entries[0]);writeLibrary(s,lib);assert.throws(()=>readLibrary(s));});
