import {brandLockup} from '../design/logo';
import {esc} from '../html';
import {isApproved} from '../model';
import {visibleEntries,type Library,type LibraryFilter} from './library';
import type {Language} from '../i18n';
import {homeCopy} from './home-copy';
const art='/brand/cutouts/';
export function projectCards(library:Library,filter:LibraryFilter,query:string,language:Language='en'){
  const t=homeCopy[language];
  const entries=visibleEntries(library,filter,query);
  return entries.length?entries.map(({project:p,updatedAt,pinned,archived})=>{
    const blocks=p.pages[0].blocks,photo=blocks.find(b=>b.image)?.image||p.reference;
    return `<article class="folio-card" data-project-id="${esc(p.id)}"><a href="#" class="folio-open" data-action="hub-open" data-id="${esc(p.id)}" aria-label="${t.open} ${esc(p.name)}"><div class="folio-preview" style="--preview-paper:${p.system.background};--preview-ink:${p.system.foreground};--preview-accent:${p.system.accent};background:${p.system.background};color:${p.system.foreground}">${photo?`<img src="${esc(photo)}" alt="" loading="lazy">`:`<div class="folio-type"><small>${esc(p.system.name)}</small><strong>${esc(blocks.find(b=>b.kind==='hero')?.title||p.name)}</strong><div class="folio-lines"><i style="background:${p.system.accent}"></i><i></i><i></i></div></div>`}<span class="folio-preview-label">${t.preview}</span></div><div class="folio-info"><h3>${esc(p.name)}</h3><span>${p.pages.length} ${language==='en'&&p.pages.length===1?'page':t.pages} <b>·</b> ${esc(p.system.name)}</span></div></a><div class="folio-meta"><span>${isApproved(p)?t.approved:t.draft} · ${esc(updatedAt.slice(0,10))}</span><button data-action="hub-pin" data-id="${esc(p.id)}" aria-label="${pinned?t.unpin:t.pin} ${esc(p.name)}" aria-pressed="${pinned}">${pinned?'★':'☆'}</button></div><div class="folio-tools"><button data-action="vault-open" data-id="${esc(p.id)}">${t.files}</button><button data-action="hub-rename" data-id="${esc(p.id)}">${t.rename}</button><button data-action="hub-duplicate" data-id="${esc(p.id)}">${t.duplicate}</button><button data-action="hub-archive" data-id="${esc(p.id)}">${archived?t.restore:t.archive}</button></div></article>`;
  }).join(''):`<div class="folio-empty"><img src="${art}apple-hand.png" alt="" width="180" height="180"><h3>${query?t.emptySearch:filter==='archived'?t.emptyArchive:filter==='pinned'?t.emptyPinned:t.emptyRecent}</h3><p>${query?t.searchHint:filter==='recent'?t.startHint:t.organizeHint}</p>${!query&&filter==='recent'?`<button class="folio-primary" data-action="new-project">${t.first} ↗</button>`:''}</div>`;
}
export function workspaceHome(library:Library,filter:LibraryFilter,query:string,error:string,night=false,language:Language='en'){
  const t=homeCopy[language];
  const active=library.entries.filter(e=>!e.archived).length;
  return `<div class="folio-home ${night?'folio-night':''}"><aside class="folio-sidebar"><a class="folio-wordmark" href="#" data-action="home" aria-label="Aphrodite projects">${brandLockup}</a><div class="folio-workspace"><span class="folio-avatar">a.</span><div>${t.workspace}<small>${t.local}</small></div></div><nav aria-label="${t.sections}">${(['recent','pinned','archived'] as const).map((f,i)=>`<button data-action="hub-filter" data-filter="${f}" aria-current="${filter===f?'page':'false'}"><span>${['▦','☆','▱'][i]}</span>${t.filters[i]}${f==='recent'?`<small>${active}</small>`:''}</button>`).join('')}</nav><div class="folio-side-note"><img src="${art}paper-dove.png" alt="" width="170" height="170"><p>${t.note}</p><button data-action="brand-kit">${t.muse} ↗</button></div><footer><span class="folio-dot"></span> ${t.saved}<small>${t.backup}</small></footer></aside><main class="folio-main"><header class="folio-top"><span>${t.space}</span><div><button data-action="language-settings" aria-label="Language / 언어">EN / 한국어</button> <button data-action="hub-theme" aria-pressed="${night}">${night?'☀ '+t.paper:'☾ '+t.night}</button> <button data-action="import-project">${t.import} ↗</button></div></header><section class="folio-hero"><div><span class="folio-eyebrow">${t.eyebrow}</span><h1>${t.headline}<br><em>${t.headlineEm}</em></h1><p>${t.intro}</p><div class="folio-hero-actions"><button class="folio-primary" data-action="new-project">${t.new} <span>↗</span></button><span class="folio-handwritten">${t.handwritten}</span></div></div><div class="folio-art"><img src="${art}${night?'night':'aphrodite'}.png" alt="${t.artAlt}" width="390" height="390"><span>${t.artCaption}</span></div></section>${error?`<div class="folio-warning" role="alert"><img src="${art}recovery.png" alt="" width="72" height="72">${esc(error)} <button data-action="hub-recovery">${t.recovery}</button> <button data-action="disk-reload">${t.reload}</button></div>`:''}<section aria-labelledby="folio-project-title"><div class="folio-library-head"><div><h2 id="folio-project-title">${t.titles[filter==='recent'?0:filter==='pinned'?1:2]}<span> / ${visibleEntries(library,filter,'').length.toString().padStart(2,'0')}</span></h2><p>${t.collection}</p></div><label class="folio-search"><span>⌕</span><input id="project-search" type="search" aria-label="${t.search}" placeholder="${t.placeholder}" value="${esc(query)}"></label></div><div class="folio-grid" id="project-grid">${projectCards(library,filter,query,language)}</div></section><footer class="folio-bottom"><span>${t.footer}</span><span>${t.credit} ✳</span></footer></main></div>`;
}
