import {catalog,type BlockKind,type Project} from '../model';
import {esc} from '../html';
import {catalogGroup,catalogGroups,catalogPreviewSize,implementations,type CatalogChoice} from './component-explorer';
import {patternVariants} from '../patterns';
import {providers} from '../providers';
import {filteredKinds,emptyCatalogFilter,type CatalogFilter} from './catalog-filter';

/** Presentation only: opening the catalog never mutates a project or approval. */
export function catalogView(p:Project,kind:BlockKind,variant:string,group:string,ui:(en:string,ko:string)=>string,preview:(choice:CatalogChoice)=>string,filter:CatalogFilter=emptyCatalogFilter){
 const kinds=filteredKinds(group,filter),rows=kinds.length?implementations(kind).filter(r=>filter.provider==='all'||r.provider===filter.provider):[];
 const labels:Record<string,string>={All:'전체',Layout:'레이아웃',Navigation:'탐색',Input:'입력',Feedback:'피드백','Content & data':'콘텐츠·데이터','App recipes':'앱 레시피'};
 const title=catalog.find(c=>c.kind===kind)!;
 const previewSize=catalogPreviewSize(kind);
 const indexCount=(k:typeof kind)=>implementations(k).filter(r=>filter.provider==='all'||filter.provider===r.provider).length;
 const indexGroups=catalogGroups.map(g=>[g,kinds.filter(c=>catalogGroup(c.kind)===g)] as const).filter(([,items])=>items.length);
 const indexTitle=ui('Implementations · options (implementations × variations)','구현 수 · 옵션 수 (구현 × 변형)');
 const kindButton=(c:(typeof kinds)[number])=>`<button data-action="explorer-kind-pick" data-kind="${c.kind}" aria-label="Browse ${c.kind}" aria-pressed="${kind===c.kind}"><span>${esc(c.name)}</span><small title="${indexTitle}">${String(indexCount(c.kind)).padStart(2,'0')}<i>·${indexCount(c.kind)*patternVariants(c.kind).length}</i></small></button>`;
 return `<div class="catalog-topline"><nav class="catalog-categories" aria-label="Catalog categories">${Object.keys(labels).map(g=>`<button data-action="explorer-group" data-group="${g}" aria-pressed="${group===g}">${ui(g,labels[g])}</button>`).join('')}</nav><button class="catalog-shelf-link" data-action="close-modal" data-shelf-count></button></div>
 <form id="catalog-filter-form" class="catalog-filters"><label>${ui('Find a component','컴포넌트 찾기')}<input name="query" aria-label="Search catalog" placeholder="${ui('Button, input, card…','버튼, 입력, 카드…')}" value="${esc(filter.query)}" maxlength="100"></label><label>${ui('Design system','디자인 시스템')}<select name="provider" aria-label="Filter design system"><option value="all">${ui('All systems','모든 시스템')}</option>${Object.entries(providers).map(([id,p])=>`<option value="${id}" ${filter.provider===id?'selected':''}>${esc(p.name.split(' · ')[0])}</option>`).join('')}</select></label><button type="submit">${ui('Search','검색')}</button><button type="button" data-action="explorer-reset">${ui('Reset','초기화')}</button><span role="status">${kinds.length} ${ui('types','개 종류')}</span></form>
 <div class="catalog-layout"><aside class="catalog-index" aria-label="Component index"><span class="catalog-eyebrow">${ui('THE INDEX','컴포넌트 인덱스')}</span>${indexGroups.map(([g,items])=>`<h4 class="catalog-index-group">${ui(g,labels[g]??g)}</h4>${items.map(kindButton).join('')}`).join('')}<div class="catalog-brand"><span class="catalog-eyebrow">${ui('YOUR PROJECT','프로젝트 테마')}</span><strong>${esc(p.system.name)}</strong><div>${[p.system.accent,p.system.background,p.system.foreground].map(color=>`<i style="background:${color}" title="${color}"></i>`).join('')}<code>${esc(p.system.accent)}</code></div><button data-action="systems">${ui('Edit design system ↗','디자인 시스템 설정 ↗')}</button></div></aside>
 <section class="catalog-results" aria-label="Catalog results"><div class="catalog-results-heading"><div><span class="catalog-eyebrow">${esc(catalogGroup(kind))} / ${String(rows.length).padStart(2,'0')} ${ui('IMPLEMENTATIONS','개의 구현')} · ${rows.length*patternVariants(kind).length} ${ui('OPTIONS','개 옵션')}</span><h3>${rows.length?esc(title.name):ui("No results","검색 결과 없음")}<span>.</span></h3><p>${ui("Compare the same form across systems. Keep your project identity.","같은 형태를 시스템별로 비교하세요. 프로젝트의 개성은 유지됩니다.")}</p></div><label class="catalog-variant">${ui('Variation','변형')}<select id="explorer-variant" aria-label="Explorer variation" ${rows.length?'':'disabled'}>${patternVariants(kind).map(v=>`<option ${v===variant?'selected':''}>${esc(v)}</option>`).join('')}</select></label></div>
 <div class="explorer-grid" data-preview-kind="${kind}" data-preview-size="${previewSize}">${!rows.length?`<p class="catalog-empty" role="status">${ui('No matching components. Reset filters or choose another category.','일치하는 컴포넌트가 없습니다. 필터를 초기화하거나 다른 카테고리를 선택하세요.')}</p>`:''}${rows.map((row,index)=>{
 const attrs=`data-kind="${kind}" data-provider="${row.provider}" data-variant="${variant}"`;
 const name=row.provider==='own'?'Aphrodite':row.provider==='shadcn'?'shadcn/ui':row.provider==='astryx'?'Astryx':row.provider.toUpperCase();
 return `<article class="explorer-card" data-kind="${kind}" data-preview-size="${previewSize}" aria-label="${row.provider} ${kind} ${variant}"><header><div><span class="catalog-provider-mark" aria-hidden="true">${row.provider==='own'?'a.':name.slice(0,1)}</span><strong>${name}</strong></div><span class="catalog-origin">${row.provider==='own'?ui('STUDIO','자체 구현'):row.provider==='shadcn'?ui('ADAPTED','소스 기반'):ui('OFFICIAL','공식 라이브러리')}</span></header><div class="catalog-stage"><div class="explorer-preview" inert aria-hidden="true">${preview({kind,provider:row.provider,variant})}</div><button class="catalog-inspect" data-action="explorer-inspect" ${attrs} aria-label="Inspect ${row.provider} ${kind} ${variant}">${ui('Full preview','크게 보기')} ↗</button></div><footer><div class="catalog-variants" role="group" aria-label="${ui('Variations','변형')}">${patternVariants(kind).map(v=>`<button type="button" class="catalog-chip" data-action="explorer-variant-pick" data-variant="${esc(v)}" aria-pressed="${v===variant}">${esc(v)}</button>`).join('')}</div><div class="catalog-card-meta"><code>${esc(kind)} / ${esc(variant)}</code><span class="catalog-theme ${row.theme==='native'?'native':''}">${row.theme==='native'?ui('Source palette','고유 색상'):ui('Project palette','프로젝트 색상')}</span></div><div class="catalog-card-actions"><button class="secondary-button" data-action="explorer-pin" ${attrs} aria-label="Pin ${row.provider} ${kind} ${variant}">${ui('Pin to shelf','선반에 담기')}</button><button class="primary-button" data-action="explorer-add" ${attrs} aria-label="Add ${row.provider} ${kind} ${variant}">${ui('Add to page','페이지에 추가')} +</button></div><small class="catalog-source" title="${esc(row.source)}">${String(index+1).padStart(2,'0')} · ${esc(row.source)}</small></footer></article>`;
 }).join('')}</div><p class="catalog-disclosure">${ui('Real renderers, not screenshots. Inspect, collect, then compose. Only implemented adapters are shown; source palettes and variant mappings may differ. HIG is guidance, not a library.','스크린샷이 아닌 실제 렌더러입니다. 크게 확인하고, 모아서, 조립하세요. 구현된 어댑터만 표시하며 고유 색상·변형 매핑은 DS마다 다릅니다. HIG는 라이브러리가 아닌 가이드입니다.')}</p></section></div>`;
}
