import {esc} from '../html';
import {referenceSources} from './bridge';
import {vibePacks,type VibePlan} from './vibe';
export function bridgeHtml(){return `<h3>oh-my-design · Local source bridge</h3><p>기업 토큰의 출처를 보존하는 오프라인 스냅샷입니다. 실시간 MCP 연결이나 전체 DS 이식은 아닙니다.</p><div class="design-grid">${referenceSources.map(s=>`<article class="design-tile"><small>REFERENCE · NOT A FULL IMPLEMENTATION</small><h3>${esc(s.name)}</h3><p>${esc(s.scope)}</p><p>적용: ${esc(s.adopted.join(', '))}</p><p>미지원: ${esc(s.unmapped.join(', '))}</p><small>SHA-256 ${s.sha256.slice(0,12)}…</small><div><button class="secondary-button" data-action="apply-omd" data-source="${s.id}">Apply ${s.id} source</button><button class="plain-button" data-action="omd-issue" data-source="${s.id}">Issue proposal</button></div></article>`).join('')}</div><div class="vibe-actions"><button class="secondary-button" data-action="brand-kit">Aphrodite brand kit</button><button class="secondary-button" data-action="import-md">Import DESIGN.md</button></div>`;}
export function vibeFormHtml(image:boolean){return `<form id="vibe-form"><label class="form-label">Content direction<select name="pack">${vibePacks.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><div class="design-grid">${vibePacks.map(p=>`<div class="design-tile"><strong>${esc(p.name)}</strong><p>${esc(p.description)}</p></div>`).join('')}</div><label class="check-option"><input name="copy" type="checkbox" checked>제목·더미 텍스트·버튼·입력 라벨 채우기</label><label class="check-option"><input name="images" type="checkbox" checked>번들 또는 업로드 이미지로 Hero / Collection 슬롯 채우기</label><div class="vibe-actions"><button type="button" class="secondary-button" data-action="vibe-image">${image?'Replace image':'Choose image'}</button>${image?'<span>이미지 준비됨 · 임시 선택, 적용 전 저장되지 않음</span>':'<span>Lighting Hero 생성 사진 1종 제공 · 다른 슬롯은 미확보로 표시</span>'}</div><label class="check-option"><input name="replace" type="checkbox">작성된 콘텐츠도 교체 (기본: 보호)</label><p class="design-warning">로컬 자체 작성 샘플입니다. 이미지 분석·OCR 전사·AI 생성은 이 버튼에서 호출하지 않습니다. 이미지 권리는 업로드한 사용자가 확인해야 합니다.</p><button class="primary-button full-width" type="submit">Preview Get Vibe changes</button></form>`;}
export function vibePreviewHtml(plan:VibePlan){return `<p>${plan.changes.length}개 필드 변경 · 미지원 컴포넌트 ${plan.unsupported.length}개 · 요청한 이미지 중 미확보 슬롯 ${plan.missingAssets.length}개</p><table class="vibe-diff"><thead><tr><th>대상</th><th>기존</th><th>변경</th></tr></thead><tbody>${plan.changes.map(c=>`<tr><td>${esc(c.id.slice(0,8))} / ${c.field}</td><td>${c.field==='image'?'기존 이미지':esc(c.before)}</td><td>${c.field==='image'?(c.after.startsWith('data:')?'사용자 업로드 이미지':'번들 생성 사진'):esc(c.after)}</td></tr>`).join('')}</tbody></table><div class="vibe-actions"><button class="secondary-button" data-action="autofill">Back</button><button class="primary-button" data-action="apply-vibe" ${plan.changes.length?'':'disabled'}>Apply ${plan.changes.length} changes</button></div><p>현재 페이지만 변경합니다. 배치·컴포넌트 ID·기업 토큰은 유지되고 한 번의 Undo로 되돌릴 수 있습니다.</p>`;}
export function brandHtml(language:'en'|'ko'='en'){
  const ko=language==='ko';
  const t=(en:string,k:string)=>ko?k:en;
  const swatch=(name:string,hex:string,use:string)=>`<li class="brand-swatch" style="--swatch:${hex}"><i></i><strong>${name}</strong><code>${hex.toUpperCase()}</code><small>${use}</small></li>`;
  const cut=(file:string,title:string,use:string)=>`<figure class="brand-cutout"><img src="/brand/cutouts/${file}" alt="${title}" loading="lazy"><figcaption><strong>${title}</strong><span>${use}</span></figcaption></figure>`;
  return `<div class="brand-kit">
<section class="brand-hero"><img src="/brand/cutouts/aphrodite.png" width="512" height="512" alt="${t('Aphrodite newspaper collage wearing sunglasses','선글라스를 쓴 아프로디테 신문 콜라주')}"><div><span class="brand-eyebrow">APHRODITE · PAPER MUSE</span><h3>Old soul. Fresh ideas.</h3><p>${t('Classical beauty with one playful cut. Newsprint halftone, torn paper edges, a golden apple.','고전의 아름다움에, 가벼운 장난 한 조각. 신문 망점 · 종이의 단면 · 황금사과.')}</p><p class="brand-hero-note">${t('Aphrodite is the muse of the studio: she judges taste, the agent does the assembling, you decide.','아프로디테는 스튜디오의 뮤즈입니다. 취향을 가늠하고, 에이전트가 조립하고, 결정은 사람이 합니다.')}</p></div></section>
<section class="brand-section"><header><h4>${t('Identity','아이덴티티')}</h4><p>${t('Wordmark, mark and app icon. Keep the apple golden; never recolour the ink.','워드마크·심볼·앱 아이콘. 사과는 항상 금색, 잉크색은 바꾸지 않습니다.')}</p></header><div class="brand-lockups"><figure class="brand-lockup paper"><img src="/brand/apple-a-lockup.svg" alt="Aphrodite wordmark"><figcaption>${t('Wordmark · on paper','워드마크 · 종이 위')}</figcaption></figure><figure class="brand-lockup mascot"><img src="/brand/pearl-mascot.svg" alt="Pearl, the Aphrodite mascot"><figcaption>${t('Pearl · the mascot','펄 · 마스코트')}</figcaption></figure><figure class="brand-lockup mark"><img src="/brand/aphrodite-mark.svg" alt="Aphrodite mark"><figcaption>${t('Mark · the engraved apple','심볼 · 인그레이빙 사과')}</figcaption></figure><figure class="brand-lockup icon"><img src="/brand/app-icon-1024.png" alt="Aphrodite app icon"><figcaption>${t('macOS app icon','macOS 앱 아이콘')}</figcaption></figure></div></section>
<section class="brand-section"><header><h4>${t('Colour','색')}</h4><p>${t('Three brand colours and two working greys. Apple is an accent, never a background for text.','브랜드 색 세 가지와 작업용 회색 둘. 사과색은 강조용이며 글자 배경으로 쓰지 않습니다.')}</p></header><ul class="brand-swatches">${swatch('Ink','#292820',t('Text, wordmark, primary buttons','텍스트·워드마크·기본 버튼'))}${swatch('Paper','#f7f5ef',t('Page ground, cards','페이지 바탕·카드'))}${swatch('Apple','#d7b449',t('Accent, handwriting, the apple','강조·손글씨·사과'))}${swatch('Moss','#3a4531',t('Secondary text, chrome','보조 텍스트·크롬'))}${swatch('Dove','#ebeee4',t('Canvas, dividers','캔버스·구분선'))}</ul></section>
<section class="brand-section"><header><h4>${t('Type','서체')}</h4><p>${t('A warm serif for headlines, a quiet sans for the interface, a handwritten note for the human touch.','제목은 따뜻한 세리프, 인터페이스는 조용한 산세리프, 손글씨 한 줄로 사람의 온기를 더합니다.')}</p></header><div class="brand-type"><p class="brand-type-serif">Shape before you build. <span>Fraunces · Iowan Old Style · ${t('Korean: Apple Myungjo / Noto Serif KR','한글: Apple 명조 / Noto Serif KR')}</span></p><p class="brand-type-sans">${t('Find a direction and make it together.','방향을 잡고, 함께 만드세요.')} <span>Geist · -apple-system · Apple SD Gothic Neo</span></p><p class="brand-type-hand">make something yours. <span>Reenie Beanie · ${t('always in English','언어와 무관하게 영문 유지')}</span></p><p class="brand-type-mono">aphrodite.hero / split · v1 <span>Geist Mono · ui-monospace</span></p></div></section>
<section class="brand-section"><header><h4>${t('Voice','목소리')}</h4><p>${t('Short, warm, decided. We say what happens, not how clever the tool is.','짧고, 따뜻하고, 단호하게. 도구가 얼마나 똑똑한지가 아니라 무슨 일이 일어나는지를 말합니다.')}</p></header><ul class="brand-voice"><li><strong>Shape before you build.</strong><span>${t('Tagline · landing, window title','태그라인 · 랜딩·창 제목')}</span></li><li><strong>Good taste. Great beginnings.</strong><span>${t('Home headline','홈 헤드라인')}</span></li><li><strong>Made with intention. A little instinct, too.</strong><span>${t('Footer credit','푸터 크레딧')}</span></li></ul></section>
<section class="brand-section"><header><h4>${t('Cutouts','컷아웃')}</h4><p>${t('Newspaper collage pieces. Use them large on paper, one per screen, never as icons.','신문 콜라주 조각들. 종이 위에 크게, 한 화면에 하나만, 아이콘으로는 쓰지 않습니다.')}</p></header><div class="brand-cutouts">${cut('aphrodite.png',t('The muse','뮤즈'),t('Home hero, brand kit','홈 히어로·브랜드 리소스'))}${cut('apple-hand.png',t('A new beginning','새로운 시작'),t('Empty states, new project','빈 상태·새 프로젝트'))}${cut('paper-dove.png',t('A place for ideas','아이디어가 머무는 자리'),t('Sidebar note, archive','사이드바 노트·보관함'))}${cut('night.png',t('Midnight','미드나이트'),t('Home hero in the Midnight theme','미드나이트 테마의 홈 히어로'))}${cut('review.png',t('The lens','렌즈'),t('Approval card, review','승인 카드·리뷰'))}${cut('recovery.png',t('Recovery','복구'),t('Disk warnings, recovery','디스크 경고·복구'))}</div></section>
<section class="brand-section brand-rules"><header><h4>${t('Do · Don\'t','이렇게 · 이렇게는 말고')}</h4></header><div class="brand-rule-grid"><ul><li>${t('Give the cutouts room; paper texture shows through.','컷아웃에 여백을 주세요. 종이 질감이 드러나야 합니다.')}</li><li>${t('Pair one serif headline with sans body.','세리프 제목 하나에 산세리프 본문을 짝지으세요.')}</li><li>${t('Say "Aphrodite"; the slug aphrodite-mela stays in URLs only.','제품명은 "Aphrodite". aphrodite-mela는 URL에서만 씁니다.')}</li></ul><ul class="dont"><li>${t('No gradients, no drop shadows on the cutouts.','컷아웃에 그라디언트·그림자를 얹지 않습니다.')}</li><li>${t('No colour on the sculpture; only the apple is gold.','조각상에 색을 입히지 않습니다. 금색은 사과뿐.')}</li><li>${t('No exclamation marks in product copy.','제품 문구에 느낌표를 쓰지 않습니다.')}</li></ul></div></section>
</div>`;}
