import {esc} from '../html';
import type {Language} from '../i18n';
import {vibePacks,type VibePlan} from './vibe';
const names:Record<Language,Record<string,string>>={en:{lighting:'Light atelier',commerce:'Everyday commerce',travel:'Slow travel',workspace:'Team workspace'},ko:{lighting:'빛의 아틀리에',commerce:'일상의 상점',travel:'느린 여행',workspace:'팀 워크스페이스'}};
export function vibeLanguageFormHtml(image:boolean,language:Language='en',ui:Language='en'){
 const ko=ui==='ko';
 return `<form id="vibe-form"><label class="form-label">${ko?'콘텐츠 언어':'Content language'}<select name="language" aria-label="${ko?'콘텐츠 언어':'Content language'}"><option value="en" ${language==='en'?'selected':''}>English</option><option value="ko" ${language==='ko'?'selected':''}>한국어</option></select></label><p>${ko?'새 샘플 문구에 적용되며, 기존 콘텐츠는 자동 번역하지 않습니다. 적용 시 프로젝트 언어가 저장됩니다.':'Used for new sample copy, not automatic translation. Applying changes saves this project preference.'}</p><label class="form-label">${ko?'콘텐츠 방향':'Content direction'}<select name="pack">${vibePacks.map(p=>`<option value="${p.id}">${esc(names[ui][p.id]??p.name)}</option>`).join('')}</select></label><label class="check-option"><input name="copy" type="checkbox" checked>${ko?'제목·더미 텍스트·버튼·입력 라벨 채우기':'Fill headings, sample text, buttons and input labels'}</label><label class="check-option"><input name="images" type="checkbox" checked>${ko?'준비된 이미지로 Hero / Collection 슬롯 채우기':'Fill Hero / Collection slots with available images'}</label><div class="vibe-actions"><button type="button" class="secondary-button" data-action="vibe-image">${ko?(image?'이미지 교체':'이미지 선택'):(image?'Replace image':'Choose image')}</button><span>${ko?(image?'이미지 준비됨 · 적용 전에는 저장되지 않음':'Lighting Hero 사진 1종 제공 · 다른 슬롯은 미확보로 표시'):(image?'Image ready · not saved until applied':'One Lighting Hero photo included · other unavailable slots are reported')}</span></div><label class="check-option"><input name="replace" type="checkbox">${ko?'작성된 콘텐츠도 교체 (기본: 보호)':'Replace existing content (protected by default)'}</label><p class="design-warning">${ko?'로컬 자체 작성 샘플입니다. 이 버튼은 이미지 분석·OCR·AI 생성을 호출하지 않습니다. 업로드 이미지의 권리는 사용자가 확인해야 합니다.':'Locally authored samples. This button does not run image analysis, OCR or AI generation. You are responsible for rights to uploaded images.'}</p><button class="primary-button full-width" type="submit">${ko?'Get Vibe 변경 미리보기':'Preview Get Vibe changes'}</button></form>`;
}
export function localizedVibePreviewHtml(plan:VibePlan,ui:Language='en',unsupportedNames:string[]=[],replaceChecked=false){
 const ko=ui==='ko';
 const why=plan.changes.length?'':`<div class="vibe-empty" role="status"><strong>${ko?'바뀌는 필드가 없습니다.':'Nothing would change.'}</strong><p>${ko?'작성된 문구는 기본적으로 보호됩니다. 이미 채워진 페이지에 샘플을 덮어쓰려면 “작성된 콘텐츠도 교체”를 켜세요.':'Authored copy is protected by default. To overwrite an already-filled page with sample copy, turn on “Replace existing content”.'}${unsupportedNames.length?` ${ko?'이 팩에 샘플이 없는 컴포넌트':'Components this pack has no sample for'}: ${esc(unsupportedNames.join(', '))}.`:''}</p>${replaceChecked?'':`<button type="button" class="secondary-button" data-action="vibe-retry-replace">${ko?'교체 포함해서 다시 미리보기':'Preview again, replacing existing content'}</button>`}</div>`;
 return why+`<p>${ko?`${plan.changes.length}개 필드 변경 · 미지원 컴포넌트 ${plan.unsupported.length}개${unsupportedNames.length?` (${esc(unsupportedNames.join(', '))})`:''} · ${plan.imagesRequested?`미확보 이미지 슬롯 ${plan.missingImageSlots.length}개`:`이미지 확인 안 함`}`:`${plan.changes.length} field changes · ${plan.unsupported.length} unsupported components${unsupportedNames.length?` (${esc(unsupportedNames.join(', '))})`:''} · ${plan.imagesRequested?`${plan.missingImageSlots.length} unavailable image slots`:`Images not checked`}`}</p><table class="vibe-diff"><thead><tr>${(ko?['대상','기존','변경']:['Target','Before','After']).map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${plan.changes.map(c=>`<tr><td>${esc(c.id.slice(0,8))} / ${esc(c.field)}</td><td>${c.field==='image'?(ko?'기존 이미지':'Existing image'):esc(c.before)}</td><td>${c.field==='image'?(c.after.startsWith('data:')?(ko?'업로드 이미지':'Uploaded image'):(ko?'번들 사진':'Bundled photo')):esc(c.after)}</td></tr>`).join('')}</tbody></table><div class="vibe-actions"><button class="secondary-button" data-action="vibe-back">${ko?'돌아가기':'Back'}</button><button class="primary-button" data-action="apply-vibe" ${plan.changes.length?'':'disabled'}>${ko?`${plan.changes.length}개 변경 적용`:`Apply ${plan.changes.length} changes`}</button></div><p>${ko?'현재 페이지만 변경합니다. 배치·컴포넌트 ID·기업 토큰은 유지되며 한 번의 실행 취소로 되돌릴 수 있습니다.':'Only the current page changes. Layout, component IDs and company tokens are preserved. One Undo restores the previous state.'}</p>`;
}
