import type {Block} from './model';
const e=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function moaHtml(b:Block,selected?:Block):string{
 const t=e(b.title),l=e(b.label);
 if(b.kind==='moasidebar')return `<aside class="moa-sidebar"><div class="moa-logo"><span>◆</span>${t}</div><div class="moa-team">P <strong>${e(b.text)}</strong><span>⌄</span></div><nav aria-label="워크스페이스 탐색"><span>♙　내 작업</span><strong>▦　주간 보드</strong><span>▱　프로젝트</span><span>♧　팀 멤버</span></nav><small>내 프로젝트</small><p>🟢 웹사이트 개편</p><p>🟣 디자인 시스템</p><p>🟠 제품 출시</p><footer><small>${l} · 샘플</small><p><i class="moa-avatar">JI</i> 지연 <small>프로덕트 팀</small></p></footer></aside>`;
 if(b.kind==='moatoolbar')return `<header class="moa-toolbar"><div class="moa-breadcrumb">워크스페이스 <span>/</span> <b>${l}</b><label>⌕ <input data-moa-search type="search" aria-label="작업 검색" placeholder="작업 검색"></label></div><div class="moa-heading"><div><h1>${t}</h1><p>${e(b.text)}</p></div><span class="moa-avatar">JI</span><span class="moa-avatar violet">MK</span></div><div class="moa-controls"><div class="moa-views"><button data-moa-view="board" aria-pressed="true">▦ 보드</button><button data-moa-view="list" aria-pressed="false">☰ 리스트</button></div><label>상태 <select data-moa-filter aria-label="업무 상태 필터"><option value="">전체</option><option>진행 중</option><option>검토 대기</option><option>완료</option></select></label></div><div class="moa-stats">${['진행 중','검토 대기','완료'].map((s,i)=>`<div><span class="moa-dot d${i}"></span>${s}<strong data-moa-count="${s}">—</strong></div>`).join('')}</div><p class="moa-results" data-moa-results role="status"></p></header>`;
 if(b.kind==='moacard'){const [project='',description='',owner='지연',status='진행 중',priority='보통']=b.text.split('|');return `<button class="moa-card" data-moa-task="${e(b.id)}" data-owner="${e(owner)}" data-status="${e(status)}" data-priority="${e(priority)}" data-description="${e(description)}" aria-pressed="false"><span class="moa-tag ${project.includes('웹')?'green':project.includes('출시')?'orange':'purple'}">${e(project)}</span><h3>${t}</h3><p>${e(description)}</p><small>◷ ${l}</small><div><span>${priority==='높음'?'⇈':'⌃'} ${e(priority)}</span><span class="moa-avatar" data-moa-owner>${e(owner.slice(0,1))}</span></div><small class="moa-card-status" data-moa-status>${e(status)}</small></button>`;}
 if(b.kind==='moadetail'){const [project='',description='',owner='',status='']=selected?.text.split('|')??[];return `<aside class="moa-detail" aria-label="${t}"><div class="moa-detail-top"><small>${t}</small><button data-moa-close aria-label="상세 닫기">×</button></div><div data-moa-detail-body>${selected?`<span class="moa-tag purple">${e(project)}</span><h2>${e(selected.title)}</h2><p class="moa-property">상태 <b>${e(status)}</b></p><p class="moa-property">담당자 <b>${e(owner)}</b></p><h4>설명</h4><p class="moa-description">${e(description)}</p><h4>체크리스트　1/3</h4><p class="moa-check">☑ 현재 흐름 분석</p><p class="moa-check">□ 핵심 화면 정리</p><p class="moa-check">□ 팀 리뷰 요청</p>`:`<p>${e(b.text)}</p>`}</div><small class="moa-session-note">${l}</small></aside>`;}
 return '';
}
