import type { Block } from './model';
import { patternSpecs } from './patterns';
import {moaHtml} from './moa-render';
const e = (s: string) => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const rows = (s: string) => s.split('\n').filter(Boolean).slice(0, 50).map(r => r.split('|'));
const pct = (s: string | undefined) => { const v = Number(s); return Number.isFinite(v) ? Math.min(100, Math.max(0, v)) : 0; };
const num = (s: string | undefined, d = 0) => { const v = Number(s); return Number.isFinite(v) ? v : d; };
const toneOf = (s: string | undefined) => s && ['info','success','warning','error'].includes(s) ? s : '';
const initialOf = (s: string) => e((s.trim().slice(0, 1) || '?'));
export function planningHtml(text: string, variant = 'week'): string {
  const data = rows(text);
  if (variant === 'agenda') return `<ul class="kit-agenda">${data.map(([day,task,status])=>`<li><b>${e(day)}</b><span>${e(task ?? '')}</span><small>${e(status ?? '')}</small></li>`).join('')}</ul>`;
  const groups = variant === 'board' ? [...new Set(data.map(r=>r[2] || '대기'))] : ['월','화','수','목','금'];
  return `<div class="kit-planner" style="--lanes:${Math.max(1, Math.min(groups.length, 5))}">${groups.map(group=>`<section class="kit-lane"><h3>${e(group)}</h3>${data.filter(r=>(variant === 'board' ? r[2] || '대기' : r[0])===group).map(([day,task,status])=>`<article><span class="kit-dot" aria-hidden="true"></span><span>${e(task ?? '')}</span><small>${e(variant==='board'?day:status ?? '')}</small></article>`).join('')}</section>`).join('')}</div>`;
}
export function patternHtml(b: Block): string {
  if(b.kind.startsWith('moa'))return moaHtml(b);
  const t=e(b.title), p=e(b.text), l=e(b.label), id=`kit-${e(b.id)}`, state=b.options?.state ?? 'default', variant=b.variant ?? 'default';
  const disabled=state==='disabled'||state==='loading';
  const header=`<header class="kit-header"><div><span class="kit-kicker">${l}</span><h2>${t}</h2></div></header>`;
  const wrap=(body:string)=>`<section class="kit kit-${b.kind}" data-state="${e(state)}" data-density="${b.options?.density ?? 'comfortable'}" ${state==='loading'||state==='indeterminate'?'aria-busy="true" ':''}style="--columns:${b.options?.columns ?? 3}">${body}</section>`;
  const data=rows(b.text);
  const items=data.length?data:[['항목 없음','']];
  if (['cards','stats','table','calendar'].includes(b.kind) && state!=='default') return wrap(header+`<div class="kit-state" role="status" ${state==='loading'?'aria-busy="true"':''}><strong>${state==='loading'?'불러오는 중':state==='error'?'데이터를 불러오지 못했습니다':'표시할 항목이 없습니다'}</strong><p>${state==='error'?'잠시 후 다시 확인해주세요.':state==='empty'?'새 항목을 추가하면 여기에 표시됩니다.':'잠시 기다려주세요.'}</p>${state==='loading'?'<div class="kit-skel-bar"></div><div class="kit-skel-bar"></div>':''}</div>`);
  switch(b.kind) {
    case 'button': return wrap(`<button type="button" class="kit-action" aria-label="${t}" data-kit-action ${disabled?'disabled':''} ${state==='loading'?'aria-busy="true"':''}>${state==='loading'?'처리 중…':l}</button><p class="kit-action-result" role="status" hidden>${p}</p>`);
    case 'input': return wrap(`<label class="kit-field" for="${id}"><span>${t}</span><input id="${id}" type="${variant==='search'?'search':'text'}" placeholder="${l}" ${disabled?'disabled':''} ${state==='error'?'aria-invalid="true"':''} aria-describedby="${id}-help"><small id="${id}-help">${p}</small></label>`);
    case 'tabs': return wrap(`<fieldset class="kit-switch"><legend>${t}</legend>${rows(b.text).map(([label,content],i)=>`<div class="kit-switch-item"><input type="radio" id="${id}-${i}" name="${id}" ${i===0?'checked':''} ${disabled?'disabled':''}><label for="${id}-${i}">${e(label)}</label><div class="kit-switch-panel">${e(content??'')}</div></div>`).join('')}</fieldset>`);
    case 'cards': return wrap(header+`<div class="kit-grid">${rows(b.text).map(([name,description])=>`<article class="kit-card">${variant==='media'?`<div class="kit-card-media" role="img" aria-label="${e(name)}"></div>`:''}<h3>${e(name)}</h3><p>${e(description??'')}</p></article>`).join('')}</div>`);
    case 'stats': return wrap(header+`<div class="kit-grid">${rows(b.text).map(([name,value,description])=>`<article class="kit-card"><h3>${e(name)}</h3><strong class="kit-metric">${e(value??'—')}</strong><small>${e(description??'')}</small></article>`).join('')}</div>`);
    case 'table': { const table=rows(b.text); const statuses=[...new Set(table.map(r=>r[2]??''))].filter(Boolean);
      return wrap(header+`<div class="kit-table-controls"><label>검색<input type="search" data-kit-search placeholder="${l}" aria-label="${t} 검색"></label><label>상태<select data-kit-filter aria-label="${t} 상태 필터"><option value="">전체</option>${statuses.map(s=>`<option>${e(s)}</option>`).join('')}</select></label></div><div class="kit-table-scroll"><table><caption>${t}</caption><thead><tr><th scope="col">업무</th><th scope="col">담당자</th><th scope="col">상태</th></tr></thead><tbody>${table.map(([task,owner,status])=>`<tr data-kit-row data-status="${e(status??'')}"><td>${e(task)}</td><td>${e(owner??'')}</td><td><span class="kit-chip">${e(status??'')}</span></td></tr>`).join('')}</tbody></table></div><p data-kit-no-results role="status" hidden>검색 결과가 없습니다.</p>`); }
    case 'calendar': return wrap(header+planningHtml(b.text,variant));
    case 'notice': return wrap(`<div role="status" class="kit-notice-body"><span class="kit-chip">${e(state==='loading'?'처리 중':state==='empty'?'항목 없음':({info:'안내',success:'완료',warning:'주의',error:'오류'}[variant]??b.label))}</span><div><h2>${t}</h2><p>${p}</p></div></div>`);
    case 'select': return wrap(`<label class="kit-field" for="${id}"><span>${t}</span><select id="${id}" ${disabled?'disabled':''} ${state==='error'?'aria-invalid="true"':''} aria-describedby="${id}-help"><option value="">${l}</option>${items.map(([name])=>`<option>${e(name)}</option>`).join('')}</select><small id="${id}-help">${e(items[0]?.[1]??'')}</small></label>`);
    case 'checkbox': return wrap(`<fieldset class="kit-checks" ${disabled?'disabled':''}><legend>${t}</legend>${items.map(([name,description],i)=>`<label class="kit-check" for="${id}-${i}"><input id="${id}-${i}" type="checkbox" ${i===0&&state!=='indeterminate'?'checked':''} ${disabled?'disabled':''} ${state==='indeterminate'&&i===0?'aria-checked="mixed"':''}><span><strong>${e(name)}</strong><small>${e(description??'')}</small></span></label>`).join('')}</fieldset>`);
    case 'switch': return wrap(`<fieldset class="kit-switch-list" ${disabled?'disabled':''}><legend>${t}</legend>${items.map(([name,description],i)=>`<label class="kit-switch-row" for="${id}-${i}"><span><strong>${e(name)}</strong><small>${e(description??'')}</small></span><input id="${id}-${i}" type="checkbox" role="switch" aria-checked="${i===0?'true':'false'}" ${i===0?'checked':''} ${disabled?'disabled':''}></label>`).join('')}</fieldset>`);
    case 'textarea': return wrap(`<label class="kit-field" for="${id}"><span>${t}</span><textarea id="${id}" rows="4" placeholder="${l}" ${disabled?'disabled':''} ${state==='error'?'aria-invalid="true"':''} aria-describedby="${id}-help"></textarea><small id="${id}-help">${p}</small></label>`);
    case 'badge': return wrap(header+`<div class="kit-badge-row" role="list">${items.map(([name,tone])=>`<span class="kit-badge-item" role="listitem" ${toneOf(tone)?`data-tone="${toneOf(tone)}"`:''}>${e(name)}</span>`).join('')}</div>`);
    case 'avatar': return wrap(header+`<ul class="kit-avatar-row">${items.map(([name,role])=>`<li class="kit-avatar-item"><span class="kit-avatar-face" aria-hidden="true">${initialOf(name)}</span><span><strong>${e(name)}</strong><small>${e(role??'')}</small></span></li>`).join('')}</ul>`);
    case 'breadcrumb': { const crumbs=data.flat().filter(Boolean); const path=state==='truncated'&&crumbs.length>2?[crumbs[0],'…',crumbs[crumbs.length-1]]:crumbs.length?crumbs:['홈'];
      return wrap(`<nav aria-label="${t}" class="kit-crumbs"><ol>${path.map((name,i,arr)=>`<li>${i<arr.length-1&&name!=='…'&&state!=='disabled'?`<a href="#">${e(name)}</a>`:`<span ${i===arr.length-1?'aria-current="page"':''}>${e(name)}</span>`}</li>`).join('')}</ol></nav>`); }
    case 'pagination': { const pages=data.flat().filter(Boolean); const list=pages.length?pages:['1']; const current=list[0];
      const shown=variant==='compact'?[current]:list;
      return wrap(header+`<nav aria-label="${t}" class="kit-pages"><ul>${variant==='simple'?`<li><button type="button" ${disabled?'disabled':''}>이전</button></li><li><span aria-current="page">${e(current)} / ${list.length}</span></li><li><button type="button" ${disabled?'disabled':''}>다음</button></li>`:`<li><button type="button" ${disabled?'disabled':''} aria-label="이전">이전</button></li>${shown.map(name=>`<li><button type="button" ${name===current?'aria-current="page"':''} ${disabled?'disabled':''}>${e(name)}</button></li>`).join('')}<li><button type="button" ${disabled?'disabled':''} aria-label="다음">다음</button></li>`}</ul></nav>`); }
    case 'progress': return wrap(header+`<div class="kit-progress-list">${items.map(([name,value])=>{const n=pct(value);const ind=state==='indeterminate'||state==='loading';return `<div class="kit-progress-row"><span>${e(name)}</span><div class="kit-progress-track" role="progressbar" aria-label="${e(name)}" aria-valuemin="0" aria-valuemax="100" ${ind?'aria-busy="true"':`aria-valuenow="${n}"`}><span class="kit-progress-fill" ${variant==='stepped'?`data-steps="4"`:''} style="width:${ind?40:n}%"></span></div><small>${ind?'진행 중':`${n}%`}</small></div>`;}).join('')}</div>`);
    case 'skeleton': return wrap(header+`<div class="kit-skel" role="status" aria-busy="true" aria-label="${t}">${variant==='card'?`<div class="kit-skel-card"><div class="kit-skel-bar"></div><div class="kit-skel-bar"></div><div class="kit-skel-bar"></div></div>`:variant==='list'?items.map(()=>`<div class="kit-skel-row"><span class="kit-skel-bar"></span><span class="kit-skel-bar"></span></div>`).join(''):items.map(()=>`<div class="kit-skel-bar"></div>`).join('')}</div>`);
    case 'accordion': return wrap(header+`<div class="kit-acc">${items.map(([name,content],i)=>`<details class="kit-acc-item" ${i===0&&state!=='empty'?'open':''}><summary ${disabled?'aria-disabled="true"':''}>${e(name)}</summary><div class="kit-acc-panel">${e(content??'')}</div></details>`).join('')}</div>`);
    case 'chips': return wrap(header+`<div class="kit-chip-row" role="group" aria-label="${t}">${items.map(([name,selected],i)=>{const on=/\S/.test(selected??'')||i===0;return variant==='input'?`<button type="button" class="kit-chip" ${disabled?'disabled':''}>${e(name)}</button>`:`<label class="kit-chip-choice"><input type="checkbox" ${on?'checked':''} ${disabled?'disabled':''}><span class="kit-chip">${e(name)}</span></label>`;}).join('')}${variant==='input'?`<span class="kit-chip kit-chip-add" aria-hidden="true">+</span>`:''}</div>`);
    case 'slider': return wrap(header+`<div class="kit-slider-list">${items.map(([name,value,min,max])=>{const lo=num(min,0),hi=num(max,100),v=Math.min(hi,Math.max(lo,num(value,lo)));const step=variant==='stepped'?Math.max(1,Math.round((hi-lo)/4)):1;return `<label class="kit-slider-field"><span>${e(name)} <small>${v}</small></span><input type="range" min="${lo}" max="${hi}" step="${step}" value="${v}" ${disabled?'disabled':''} ${state==='error'?'aria-invalid="true"':''} aria-valuemin="${lo}" aria-valuemax="${hi}" aria-valuenow="${v}" aria-label="${e(name)}"></label>`;}).join('')}</div>`);
    case 'stepper': return wrap(header+`<ol class="kit-steps">${items.map(([name,description],i)=>`<li class="kit-step" ${i===1?'aria-current="step"':''}><span class="kit-step-index" aria-hidden="true">${i+1}</span><span><strong>${e(name)}</strong><small>${e(description??'')}</small></span></li>`).join('')}</ol>`);
    case 'toggle': return wrap(`<fieldset class="kit-toggle-group" role="radiogroup" ${disabled?'disabled':''}><legend>${t}</legend>${items.map(([name,description],i)=>`<div class="kit-toggle-item"><input type="radio" name="${id}" id="${id}-${i}" ${i===0?'checked':''} ${disabled?'disabled':''}><label for="${id}-${i}">${variant==='icons'?`<span aria-hidden="true">${initialOf(name)}</span>`:''}<strong>${e(name)}</strong>${variant==='stacked'?`<small>${e(description??'')}</small>`:''}</label></div>`).join('')}</fieldset>`);
    default: return '';
  }
}
export const defaultPlanningText=patternSpecs.calendar.text;
