/** Aphrodite-owned patterns. References inform conventions, not vendor implementations. */
import {moaSpecs} from './moa-specs';
export const patternSpecs = {
  ...moaSpecs,
  button: { name: 'Action button', icon: 'mouse-pointer-2', category: 'Inputs', variants: ['solid', 'outline', 'ghost', 'soft'], states: ['default', 'disabled', 'loading'], title: '변경 사항 저장', text: '로컬 프로토타입 동작입니다.', label: '저장', help: 'Heading: 접근성 이름 · Label: 버튼 문구 · Content: 클릭 후 표시할 안내' },
  input: { name: 'Input field', icon: 'text-cursor-input', category: 'Inputs', variants: ['outlined', 'filled', 'search', 'underlined'], states: ['default', 'disabled', 'error'], title: '프로젝트 이름', text: '팀에서 알아볼 수 있는 이름을 입력하세요.', label: '예: 모아', help: 'Heading: 입력 라벨 · Label: placeholder · Content: 도움말 / 오류' },
  tabs: { name: 'View switcher', icon: 'panel-top', category: 'Navigation', variants: ['underline', 'segmented', 'pills', 'vertical'], states: ['default', 'disabled'], title: '프로젝트 보기', text: '개요|프로젝트의 주요 내용을 확인하세요.\n활동|팀의 최근 활동을 확인하세요.\n설정|프로젝트 설정을 관리하세요.', label: '보기 선택', help: '한 줄에 탭 이름|패널 내용. 키보드 방향키로 선택할 수 있는 radio 기반 전환입니다.' },
  cards: { name: 'Content cards', icon: 'panels-top-left', category: 'Data display', variants: ['outlined', 'elevated', 'list', 'media'], states: ['default', 'empty', 'loading', 'error'], title: '팀 프로젝트', text: '웹사이트 개편|첫 화면의 방향을 검토합니다.\n디자인 시스템|팀의 공통 언어를 만듭니다.\n제품 출시|다음 단계를 함께 준비합니다.', label: '프로젝트', help: '한 줄에 카드 제목|설명. Columns로 열 수, Density로 간격을 조절합니다.' },
  stats: { name: 'Metric cards', icon: 'chart-no-axes-column', category: 'Data display', variants: ['plain', 'outlined', 'tinted', 'compact'], states: ['default', 'loading', 'empty'], title: '이번 주 요약', text: '진행 중|12|샘플 데이터\n완료|8|샘플 데이터\n대기|3|샘플 데이터', label: '샘플 지표', help: '한 줄에 지표명|값|설명. 실제 데이터 연동은 포함되지 않습니다.' },
  table: { name: 'Task table', icon: 'table', category: 'Data display', variants: ['comfortable', 'compact', 'striped', 'bordered'], states: ['default', 'empty', 'loading', 'error'], title: '팀 업무', text: '랜딩페이지 검토|지연|진행 중\n디자인 토큰 정리|민수|완료\n출시 체크리스트|서연|대기', label: '업무 검색', help: '한 줄에 업무|담당자|상태. 미리보기·export에서 검색/상태 필터가 동작합니다.' },
  calendar: { name: 'Planning board', icon: 'calendar-days', category: 'Product UI', variants: ['week', 'agenda', 'board'], states: ['default', 'empty', 'loading', 'error'], title: '이번 주 계획', text: '월|기획안 초안 작성|진행 중\n화|디자인 시안 검토|대기\n수|개발 작업 진행|진행 중\n목|중간 점검 회의|대기\n금|팀 업데이트 공유|완료', label: '제품 미리보기 · 샘플 일정', help: '한 줄에 요일|업무|상태. week/agenda/board로 배치 변경; 실제 날짜 계산·드래그 일정 변경은 범위 밖입니다.' },
  notice: { name: 'Status message', icon: 'info', category: 'Feedback', variants: ['info', 'success', 'warning', 'error'], states: ['default', 'loading', 'empty'], title: '변경 사항을 확인하세요', text: '이 화면은 실제 데이터가 아닌 시각 프로토타입입니다.', label: '안내', help: 'Heading: 상태 제목 · Content: 설명. 상태는 색상뿐 아니라 텍스트로도 표시합니다.' },
  select: { name: 'Select menu', icon: 'chevrons-up-down', category: 'Inputs', variants: ['outlined', 'filled', 'underlined'], states: ['default', 'disabled', 'error'], title: '작업 유형', text: '디자인|시각 작업을 진행합니다.\n개발|구현 작업을 진행합니다.\n운영|배포와 운영을 담당합니다.', label: '유형 선택', help: '한 줄에 옵션 이름|설명. Heading: 필드 라벨 · Label: 빈 값 안내' },
  checkbox: { name: 'Checkbox group', icon: 'square-check', category: 'Inputs', variants: ['stacked', 'inline', 'card'], states: ['default', 'disabled', 'indeterminate'], title: '알림 설정', text: '제품 업데이트|새 기능과 개선 사항을 받습니다.\n주간 요약|진행 상황을 매주 받습니다.\n마케팅|이벤트와 혜택을 받습니다.', label: '수신 항목', help: '한 줄에 항목 이름|설명. 여러 항목을 동시에 선택할 수 있습니다.' },
  switch: { name: 'Switch', icon: 'toggle-left', category: 'Inputs', variants: ['labeled', 'compact', 'stacked'], states: ['default', 'disabled', 'loading'], title: '워크스페이스 설정', text: '알림|새 활동이 있으면 알려줍니다.\n자동 저장|변경 사항을 바로 저장합니다.\n공개|팀 외부에도 표시합니다.', label: '설정', help: '한 줄에 스위치 이름|설명. Preview에서 네이티브 switch로 켜고 끌 수 있습니다.' },
  textarea: { name: 'Text area', icon: 'file-text', category: 'Inputs', variants: ['outlined', 'filled', 'minimal'], states: ['default', 'disabled', 'error'], title: '작업 메모', text: '팀과 공유할 메모를 작성하세요. 실제 저장은 포함되지 않습니다.', label: '예: 다음 주 목표', help: 'Heading: 입력 라벨 · Label: placeholder · Content: 도움말 / 오류' },
  badge: { name: 'Status badge', icon: 'badge', category: 'Data display', variants: ['solid', 'outline', 'soft'], states: ['default', 'disabled', 'empty'], title: '상태 표시', text: '진행 중|info\n검토 대기|warning\n완료|success', label: '배지', help: '한 줄에 배지 문구|톤(info/success/warning/error, 선택).' },
  avatar: { name: 'User avatar', icon: 'circle-user', category: 'Data display', variants: ['initials', 'stacked', 'labeled'], states: ['default', 'empty', 'loading'], title: '팀 멤버', text: '지연|프로덕트\n민수|디자인\n서연|엔지니어링', label: '멤버', help: '한 줄에 이름|역할. 이니셜은 이름 첫 글자로 표시합니다.' },
  breadcrumb: { name: 'Breadcrumb', icon: 'chevron-right', category: 'Navigation', variants: ['slash', 'chevron', 'pills'], states: ['default', 'disabled', 'truncated'], title: '현재 위치', text: '워크스페이스|프로젝트|디자인 시스템|토큰', label: '경로', help: '경로 항목을 | 로 구분합니다. 마지막 항목이 현재 페이지입니다.' },
  pagination: { name: 'Pagination', icon: 'ellipsis', category: 'Navigation', variants: ['numbered', 'compact', 'simple'], states: ['default', 'disabled', 'loading'], title: '페이지 이동', text: '1|2|3|4|5', label: '결과 탐색', help: '페이지 번호 또는 라벨을 | 로 구분합니다. 첫 항목이 현재 페이지입니다.' },
  progress: { name: 'Progress', icon: 'gauge', category: 'Feedback', variants: ['bar', 'labeled', 'stepped'], states: ['default', 'loading', 'indeterminate'], title: '작업 진행률', text: '업로드|64\n동기화|32\n검토|88', label: '진행 상황', help: '한 줄에 이름|0-100 값. 실제 업로드 진행은 포함되지 않습니다.' },
  skeleton: { name: 'Skeleton', icon: 'circle-dashed', category: 'Data display', variants: ['lines', 'card', 'list'], states: ['default', 'loading', 'empty'], title: '불러오는 중', text: '제목 줄\n본문 줄\n보조 줄', label: '자리 표시', help: '한 줄에 스켈레톤 블록 설명. 실제 데이터 로딩은 포함되지 않습니다.' },
  accordion: { name: 'Accordion', icon: 'chevron-down', category: 'Data display', variants: ['separated', 'flush', 'plus'], states: ['default', 'disabled', 'empty'], title: '자주 묻는 질문', text: '일정은 어떻게 공유하나요?|팀 캘린더에 표시되는 샘플 일정입니다.\n알림은 언제 오나요?|마감 하루 전에 안내하는 프로토타입입니다.\n데이터는 저장되나요?|미리보기 동작은 세션에만 유지됩니다.', label: '도움말', help: '한 줄에 제목|내용. Preview에서 네이티브 details로 열고 닫을 수 있습니다.' },
  chips: { name: 'Chip set', icon: 'tags', category: 'Data display', variants: ['choice', 'filter', 'input'], states: ['default', 'disabled', 'empty'], title: '태그', text: '디자인|선택\n개발|\n리서치|\n운영|', label: '필터', help: '한 줄에 칩 이름|선택 여부(선택). choice는 다중 선택, filter는 켜고 끄기입니다.' },
  slider: { name: 'Slider', icon: 'sliders-horizontal', category: 'Inputs', variants: ['single', 'range', 'stepped'], states: ['default', 'disabled', 'error'], title: '표시 설정', text: '투명도|40|0|100\n간격|8|0|24', label: '값 조절', help: '한 줄에 이름|값|최소|최대. range는 두 값을 함께 표시합니다.' },
  stepper: { name: 'Stepper', icon: 'list-ordered', category: 'Navigation', variants: ['horizontal', 'numbered', 'compact'], states: ['default', 'disabled', 'error'], title: '진행 단계', text: '기획|요구사항을 정리합니다.\n디자인|화면을 검토합니다.\n개발|구현을 진행합니다.\n출시|배포를 준비합니다.', label: '단계', help: '한 줄에 단계 이름|설명. 두 번째 단계가 현재 단계로 표시됩니다.' },
  toggle: { name: 'Toggle group', icon: 'toggle-right', category: 'Inputs', variants: ['segmented', 'icons', 'stacked'], states: ['default', 'disabled', 'loading'], title: '보기 전환', text: '보드|카드로 정렬합니다.\n리스트|표로 정렬합니다.\n캘린더|일정으로 정렬합니다.', label: '보기', help: '한 줄에 토글 이름|설명. 한 번에 하나만 선택하는 radio 그룹입니다.' },
} as const;
export type PatternKind = keyof typeof patternSpecs;
export const isPattern = (kind: string): kind is PatternKind => Object.hasOwn(patternSpecs, kind);
export const patternVariants = (kind: string): readonly string[] => isPattern(kind) ? patternSpecs[kind].variants : kind === 'hero' ? ['split', 'image-left', 'stacked','editorial-wide'] : kind==='products'?['default','editorial']:kind==='frame'?['default','app-shell','app-main','app-board','app-lane']:['default'];
export const patternStates = (kind: string): readonly string[] => isPattern(kind) ? patternSpecs[kind].states : ['default'];
export type PatternOptions = { density?: 'comfortable' | 'compact'; columns?: 1 | 2 | 3 | 4; state?: string; media?: 'image' | 'calendar'; mediaText?: string; placeholder?: string };
export function validOptions(value: unknown, kind: string): boolean {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const o = value as PatternOptions;
  if (Object.keys(o).some(k => !['density', 'columns', 'state', 'media', 'mediaText', 'placeholder'].includes(k))) return false;
  return (o.density === undefined || ['comfortable', 'compact'].includes(o.density)) &&
    (o.columns === undefined || [1, 2, 3, 4].includes(o.columns)) &&
    (o.state === undefined || patternStates(kind).includes(o.state)) &&
    (o.media === undefined || (kind === 'hero' && ['image', 'calendar'].includes(o.media))) &&
    (o.mediaText === undefined || (kind === 'hero' && typeof o.mediaText === 'string' && o.mediaText.length <= 20000)) &&
    (o.placeholder === undefined || (typeof o.placeholder === 'string' && o.placeholder.length <= 200));
}
